name: flutter_48_xhdq
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^1.0.9
  json_annotation: ^2.0.0
  shared_preferences: ^0.4.3
  transparent_image: ^0.1.0
  cached_network_image: ^0.5.1
  flutter_html_view: ^0.5.10
  flutter_html: ^0.8.2
  sqflite: ^0.13.0
  flutter_webview_plugin: ^0.3.0+2
  flutter_jpush: ^0.0.4
  fluttertoast: ^2.1.2
  flutter_plugin_system: ^1.0.2



dev_dependencies:
  build_runner: ^1.1.1
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - images/


